# Generated by Django 5.2.14 on 2026-05-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_category_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Заполняется при смене статуса на "Принято в работу"', null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.ImageField(blank=True, help_text='Загружается при смене статуса на "Выполнено"', null=True, upload_to='designs/%Y/%m/%d/', verbose_name='Дизайн помещения'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
    ]
